### ISSUE TITLE
Use lists instead of sets

### ISSUE THREAD

**Issue by kiwifb** [matze/pkgconfig#10]
Hi,

The usage of sets has some potential drawback in wider use. I am guessing sets have been selected to avoid duplication in the output. Sets are very good for that. However sets have drawback:
* order is not preserved. It is particularly annoying for `libraries` where is the order is often important depending on the linker
* most distutils applications take lists as argument, not sets, which mean the output of `parse` has to be cast before being useful. I cannot think of an application requiring a set, feel free to show me one.

Both problems are solved by using list instead of set on the outset. list will preserve the order and be directly consumable by distutils. Duplication could be eliminated by applying a filter before returning the final list. However, such filter would have to go from the right rather than the left (i.e. keeping latest instance rather than the first). 

After discussion with my colleagues of `sagemath` we don't think the duplication in the output is a problem. It may be less elegant but `pkg-config` itself doesn't do anything about it - and it already filters output somewhat by default. Having worked on exotic platform I can unfortunately think of scenarios in which the duplication may be useful - especially if static libraries are involved. I'll admit reducing macros could be neat but the rest is a potential hazard.

**Comment by matze** [comment]
6db04c58bf2dd860564affa4b9fd3a08239f1afb fixed this issue. The reasoning for the change are pretty well laid out so no further comments.
