### ISSUE TITLE
tarball for 1.2.0 misses the data folder

### ISSUE THREAD

**Issue by kiwifb** [matze/pkgconfig#14]
Which is important if you want to run the testsuite. We packagers like to run testsuite before installing when we can. If you are not going to ship the data folder you shouldn't ship `test.py` either.

**Comment by matze** [comment]
fe6a79b should be enough, right? At least the data folder is now part of the tarball. If you agree, I will release 1.2.1.

**Comment by kiwifb** [comment]
I think it is enough. I am fine for a new release.

**Comment by matze** [comment]
Alright, it's done.
