### ISSUE TITLE
testing issues on system defaulting to lib64

### ISSUE THREAD

**Issue by kiwifb** [matze/pkgconfig#15]
I probably relied on travis when I did that last push. Although I would have thought the "listify" pull would be the one responsible, but I definitely tested that.
```
....F.
======================================================================
FAIL: test.test_parse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/scratch2/portage/dev-python/pkgconfig-1.2.1/work/pkgconfig-1.2.1/test.py", line 47, in test_parse
    nt.assert_true('/usr/lib64' in config['library_dirs'] or not config['library_dirs'])
AssertionError: False is not true
```
because `/usr/lib64` is the default path for libraries it is omitted. on the other hand I have `/usr/lib` in `config['library_dirs']`. I think it would be better to put a non regular name in one of the fake `.pc` files (something like `/this_is_not_a real_library_path/do_not_use_me`) and test for it.

I am overall confused by the logic of that particular assert statement.

**Comment by matze** [comment]
> I am overall confused by the logic of that particular assert statement.

Why? Either the supposed libdir is in the library dirs we have to add or that particular entry does not even exist (because it's already in the system lib path).

But yes, I could come up with a path that is indeed unique and make the test pass on all systems.

**Comment by kiwifb** [comment]
I am not sure the test as written now does what you think it does. You may have been lucky before when it was sets. It feels to me that it resolves to 
```
(/usr/lib64 in config[...]) or ( not config[...])
```
I am not sure when the right element is `True`. If `config[...]` doesn't exist then I am guessing its negation is `True` but `config[...]` should never be empty with those two fake `.pc`. You should have either `/usr/lib64` or `/usr/lib` in it. What's the negation of that? Apparently `False`.

**Comment by matze** [comment]
> I am not sure the test as written now does what you think it does. 

The test as written *right* now does not even contain this.

**Comment by kiwifb** [comment]
Sorry I had started writing before the push. As it was written before you last push. I think it broke when you passed from testing with one package to testing with two with different libdirs. And I am annoyed with myself because I should have caught it much earlier. I had an hint and I thought I was doing something wrong.

**Comment by matze** [comment]
No problem. Do you want me to release this as another version?

**Comment by kiwifb** [comment]
I'll do some extra checks with the current state to be sure that we don't have to do another one after that first.

**Comment by kiwifb** [comment]
OK looks all clean now, so yes another release :( but this one looks all good :)

**Comment by matze** [comment]
Alright, 1.2.2 is up.
