### ISSUE TITLE
parse() will not  handle values with spaces correctly

### ISSUE THREAD

**Issue by tliron** [matze/pkgconfig#16]
In the .pc file, a space in a value will be escaped as "\ ".

But here we are splitting just by spaces:

https://github.com/matze/pkgconfig/blob/master/pkgconfig/pkgconfig.py#L185

**Comment by tliron** [comment]
A solution is to split with a regex (negative lookbehind):

    re.split(r'(?<!\\) ', out)

**Comment by matze** [comment]
Thanks for the report. Are you sure, your proposed patch works? I get this:
```python
>>> re.split(r'(?<!\\) ', '-I/usr/foo bar/baz')
['-I/usr/foo', 'bar/baz']
```
Still not what the user would expect I suppose.

**Comment by tliron** [comment]
The regex checks for _escaped_ spaces, which is how spaces work in .pc files:

    >>> re.split(r'(?<!\\) ', '-I/usr/foo\\ bar/baz')
    ['-I/usr/foo\\ bar/baz']

**Comment by matze** [comment]
Oh my ... thanks, I will push the fix in a sec.
