### ISSUE TITLE
Obtain libraries needed for static linking (.e.,g --static)

### ISSUE THREAD

**Issue by ericvw** [matze/pkgconfig#24]
@matze, would you be open if I expose an option to `.parse()` and `.libs()` for obtaining the libraries for static linking?

From `man pkg-config(1)`:

```
    --static
              Output libraries suitable for static linking.  That means including any private libraries in the output.  This relies on proper tagging in the .pc files, else a too large number of libraries will ordinarily be output.
```

I was thinking of something like `.parse(..., static=True)` and `.libs(..., static=True)`, with the default value being either `None` or `False`.  I'm open to your suggestions and am happy implement the change with a test case.

**Comment by matze** [comment]
Sounds about alright. I'd suggest to make the default value `False` though. `None` somehow implies that some non-boolean value could be passed as well which I don't think is the intention here.

**Comment by ericvw** [comment]
Sounds great — appreciate the timely response.  I'll work on this and have a PR soon.
