### ISSUE TITLE
Switch from nose to pytest

### ISSUE THREAD

**Issue by ericvw** [matze/pkgconfig#27]
[`nose`](https://nose.readthedocs.io/en/latest/) has been in maintenance mode over the past several years and is not actively developed (see Notes section at the top of the main page).

Given that [`pytest`](https://docs.pytest.org/en/latest/) is also mentioned in the [`unittest`](https://docs.python.org/3/library/unittest.html) documentation as an alternative test runner/framework, @matze, would be open if I migrate the tests over to `pytest`-style and structure?

**Comment by ericvw** [comment]
> Hmm, I'd say just because software is in maintenance mode does not mean it needs to be replaced for the sake of doing so.

I agree with this sentiment.

> Are there any other compelling reasons for a switch?

After looking at the current tests, https://github.com/matze/pkgconfig/blob/8af0102346847e8873af8e76ab3f34ba9da806e2/test.py#L13 could leverage https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions.  Beyond that, the assert methods from `nose` would be converted to `assert`s.

Happy to create a PR if you like; otherwise, not changing anything seems reasonable given there isn't anything substantially compelling.

**Comment by matze** [comment]
Not super-convincing but go ahead! If it covers the same tests and checks green on Travis, it can go in.
