### ISSUE TITLE
win32 (msys2) "\r" in keys for .variables()

### ISSUE THREAD

**Issue by briend** [matze/pkgconfig#30]
Hi!  Thanks for the library!  I'm hoping it will help me dynamically get a configuration variable for a package in a dynamic way from python.  I'm trying to support several platforms, and I'm having a problem specific to windows and the \r\n line feeds.

https://github.com/matze/pkgconfig/blob/master/pkgconfig/pkgconfig.py#L132

On MSYS2 (windows "unix" environment) this can be pretty ugly, leaving the keys with the string "\r" at the end of some keys (but not all keys):

>>> pkgconfig.variables('zlib')
{u'sharedlibdir': u'C:/msys64/mingw64/bin', u'exec_prefix\r': u'C:/msys64/mingw64', u'pcfiledir\r': u'C:\\msys64\\mingw64\\lib\\pkgconfig', u'includedir\r': u'C:/msys64/mingw64/include', u'libdir\r': u'C:/msys64/mingw64/lib', u'prefix\r': u'C:/msys64/mingw64'}

**Comment by matze** [comment]
Thanks for the report. Could you upload an example of a .pc file with this problem? At the moment, I cannot  imagine how the carriage returns could end up between the key and the value.

**Comment by briend** [comment]
No problem, here's the output for glew.pc, and it is attached.  I checked the pc file and it didn't have any CR.  I think it has to do with the call to pkgconfig.exe and handling the output from windows?
https://github.com/matze/pkgconfig/blob/master/pkgconfig/pkgconfig.py#L68-L73

>>> pkgconfig.variables('glew')                                                                                                                                                       {u'pcfiledir\r': u'C:\\msys64\\mingw64\\lib\\pkgconfig', u'prefix': u'C:/msys64/mingw64', u'libdir\r': u'C:/msys64/mingw64/lib', u'includedir\r': u'C:/msys64/mingw64/include', u'exe c_prefix\r': u'C:/msys64/mingw64'}
--

[glew.zip](https://github.com/matze/pkgconfig/files/2639811/glew.zip)

**Comment by matze** [comment]
Hmm, that must be the only source of those newlines. I wanted to write a test case to confirm that a possible solution works but under those circumstances I will just trim excess whitespace unconditionally …
