### ISSUE TITLE
Please expose --modversion

### ISSUE THREAD

**Issue by hughmcmaster** [matze/pkgconfig#31]
`pkg-config --modversion <package>` oututs the version information of a package's libraries.

For example, `pkg-config --modversion icu-i18n` outputs 63.1 (assuming that version is installed).

It would be very useful to be able to get this information using your pkgconfig module.

The syntax would be `pkgconfig.modversion('package')` or similar.

If you don't have time, I can look at preparing a pull request for this.

Thank you

**Comment by matze** [comment]
I don't know why you need this (there is the `installed` method after all) but there you go.

**Comment by hughmcmaster** [comment]
Thank you for doing this so quickly!

The `installed` method is normally sufficient, but there are some corner cases where it is useful to know what version of a library is installed.
