### ISSUE TITLE
use src/ project layout?

### ISSUE THREAD

**Issue by ThomasWaldmann** [matze/pkgconfig#36]
for quite some reasons it is preferable not to have the main package directory in `./pkgconfig`, but rather in `src/pkgconfig`, e.g. making sure the actually installed code is tested and not accidentally the package that happens to be in `.`.

**Comment by ThomasWaldmann** [comment]
i could contribute this after next release, if wanted.

**Comment by ThomasWaldmann** [comment]
@matze Any comment?

**Comment by matze** [comment]
Yeah, please go ahead with a PR, I have no objections!

**Comment by ThomasWaldmann** [comment]
OK, will do after #70 is merged, so we have working CI first.
