### ISSUE TITLE
_query should check exit code of pkg-info

### ISSUE THREAD

**Issue by ThomasWaldmann** [matze/pkgconfig#42]
pkginfo 1.4.0
```
>>> from pkgconfig import parse
>>> parse('openssl')  # existing lib
defaultdict(<class 'list'>, {'libraries': ['ssl', 'crypto'], ...})
>>> parse('libxxxxxxxxxx')  # non-existing lib!
defaultdict(<class 'list'>, {...})
```

for a non-existing lib (see last example), guess there could be some exception, but it fails silently.

i had a quick look and the main problem might be that `_query` does not check the exit code of `pkg-info`, which is 1 in the error case and 0 in case it is successful.

guess it should raise a relatively generic exception in the error case, so it does not fail silently.

additionally to that, maybe the calls that rely on a lib being actually there could first check if the lib is installed and if not raise a more specific exception "lib not found".

**Comment by matze** [comment]
> i had a quick look and the main problem might be that _query does not check the exit code of pkg-info, which is 1 in the error case and 0 in case it is successful.

As far as I remember that initial idea was to simulate the command line usage, i.e. check first with `pkgconfig.exists()` if the .pc file is actually installed and then use the query functions. But I guess it is not harmful to raise some `PackageNotFound` exception.

**Comment by ThomasWaldmann** [comment]
Yeah, that would work. So maybe just a matter of docs.

But I still think the _query stuff should check the rc, so that if you use it wrong, it will not silently fail.

**Comment by matze** [comment]
> But I still think the _query stuff should check the rc, so that if you use it wrong, it will not silently fail.

I think using the return code is wrong for this because it does not tell us (forever that is) what the actual problem was. So 75b6de7 calls `exists()` explicitly before querying.

**Comment by ThomasWaldmann** [comment]
Of course a 0/1 rc can't tell you much. But an error rc tells that it did not work, so running `.parse()` with that output and returning a fake result could be avoided.

**Comment by matze** [comment]
Erm 75b6de7 does not return a fake result anymore …

**Comment by timokau** [comment]
This can lead to confusing exceptions:

```
In [3]: pkgconfig.parse('fflas-ffpack')                                                                                          
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
<ipython-input-3-490bd60e0b69> in <module>
----> 1 pkgconfig.parse('fflas-ffpack')

/nix/store/glgwssry5d9f48clbb1f8ls1nsra00m3-python3-3.7.5-env/lib/python3.7/site-packages/pkgconfig/pkgconfig.py in parse(packages, static)
    249     """
    250     for package in packages.split():
--> 251         _raise_if_not_exists(package)
    252 
    253     out = _query(packages, *_build_options('--cflags --libs', static=static))

/nix/store/glgwssry5d9f48clbb1f8ls1nsra00m3-python3-3.7.5-env/lib/python3.7/site-packages/pkgconfig/pkgconfig.py in _raise_if_not_exists(package)
    104 def _raise_if_not_exists(package):
    105     if not exists(package):
--> 106         raise PackageNotFoundError(package)
    107 
    108 

PackageNotFoundError: fflas-ffpack not found
```

Leading me to think that `fflas_ffpack` could not be located while in fact the issue is with some dependency:

```
$ pkg-config --libs fflas-ffpack
Package givaro was not found in the pkg-config search path.
Perhaps you should add the directory containing `givaro.pc'
to the PKG_CONFIG_PATH environment variable
Package 'givaro', required by 'fflas-ffpack', not found
```

Maybe the original error text should be forwarded.
