### ISSUE TITLE
missing setup.py in source file from github

### ISSUE THREAD

**Issue by dirteat** [matze/pkgconfig#44]
Hi there,
the pkgconfig-1.5.1.tar.gz file from github is missing setup.py, whereas the one from pypi is fine. That's quite confusing to have 2 source files with the same name but not same content, especially when one is not compiling :-/

Cheers,
Chris.

**Comment by matze** [comment]
We do not support `setup.py` anymore. You can use `pip` or poetry directly to install the package.

**Comment by dirteat** [comment]
Hello, thank you for your answer. Sorry,  I may not get what you mean exactly. I am currently packaging pkgconfig for a linux distribution (mageia), which means we must compile and install your package out of pip or poetry, from scratch.

If you mean that we should retrieve your source files only from pypi (which provides a setup.py), fair enough, but I would then recommend that the confusing source files on github should be removed or tagged as not being compilable!?

Best,
Chris.

**Comment by dimpase** [comment]
Debian provided a setup.py for the new version here:
https://salsa.debian.org/python-team/modules/python-pkgconfig/tree/master
