### ISSUE TITLE
When is the poetry dependency needed

### ISSUE THREAD

**Issue by tdegeus** [matze/pkgconfig#54]
I was trying to update the conda-forge package and came across the added poetry dependency. However, this givens some version clash: 

https://github.com/conda-forge/pkgconfig-feedstock/pull/27

Could you comment when the poetry dependency is needed, and, may be, if and how the version clash can be overcome?

**Comment by matze** [comment]
I don't really understand what the problem is but Poetry itself is not a run-time but a build dependency. And I suspect pkg-config is not the only Python package in the Conda distribution that uses Poetry.

**Comment by tdegeus** [comment]
So it got solved in the feedstock by using `poetry_core` only in the `host` requirements.
