### ISSUE TITLE
Python3 syntax breaking use in Python2

### ISSUE THREAD

**Issue by seckwei** [matze/pkgconfig#56]
https://github.com/matze/pkgconfig/blob/af557522d83e4604c5a6a08039e221526b082333/pkgconfig/pkgconfig.py#L281

The asterisk unpacking syntax is [only available in Python3](https://www.python.org/dev/peps/pep-3132/) and it is included in the release for 1.5.3.

The README mentions pkgconfig works for Pyhon2.6+ and Python3.3+, though the [Jenkins builds](https://travis-ci.org/github/matze/pkgconfig) only have for Pyhon3.5 and above - is this not being supported for Python2 anymore?

Thanks in advance!

**Comment by matze** [comment]
> is this not being supported for Python2 anymore?

No, Python 2 is EOL'd January 2020. If you require Python 2 support, I suggest to just pin an earlier version, there have been no critical bugfixes so far. Anyhow, sorry for not updating the README.

**Comment by mariocj89** [comment]
Would it be possible to mark the package as `python_requires >=3.3` and reupload the sdist/bdist?

That will prevent breaking Python 2 users and allow you to drop Python 2 support.  I can send a PR.

**Comment by matze** [comment]
> I can send a PR.

Sure, go ahead.

**Comment by mariocj89** [comment]
#57 created, once landed you can override the past release to prevent users from falling in Python 2. 
 
 Thanks a lot for accepting this.

**Comment by matze** [comment]
> once landed you can override the past release

I don't think that's possible with PyPI. I'll just upload a new version.

**Comment by lkollar** [comment]
> I don't think that's possible with PyPI. I'll just upload a new version.

This won't help though as Python 2.7 will still pull the bad 1.5.3 version. I think there should either be a 1.5.3 post-release or that version should be yanked.

**Comment by lkollar** [comment]
Actually, I don't think the post release will help.

**Comment by pradyunsg** [comment]
I suggest yanking the offending version (1.5.3). See https://twitter.com/di_codes/status/1253166902437871616 for details (it needs logging into pypi.org, going to "manage package" for pkgconfig and clicking stuff).

The only case that won't cover is folks on old versions of pip that don't support yanking *and* Python 2... well, these are the sorts of problems you have with using outdated and EOL software -- it is their problem to solve IMO. :)

**Comment by matze** [comment]
I yanked 1.5.3, hope that helps.
