### ISSUE TITLE
Give a sensible error when pkg-config is not installed?

### ISSUE THREAD

**Issue by karolyi** [matze/pkgconfig#60]
Coming from https://github.com/yaml/pyyaml/pull/618, your package bails out hard when the `pkg-config` binary is not present on the system, which can be a case.

Could you please provide some preliminary checks and maybe a custom exception for that, please?

**Comment by matze** [comment]
> Could you please provide some preliminary checks and maybe a custom exception for that, please?

There are checks and in case the binary is not found, `EnvironmentError` is thrown. What else do you expect? Since this is a library it is expected that users handle potential exceptions.

**Comment by karolyi** [comment]
I see. The traceback I saw was somewhat convoluted for me, hence I thought it's not handled correctly.

Also, from the [EnvironmentError](https://devdocs.io/python~3.8/library/exceptions#EnvironmentError) documentation:
> The following exceptions are kept for compatibility with previous versions; starting from Python 3.3, they are aliases of [OSError](https://devdocs.io/python~3.8/library/exceptions#OSError).

**Comment by karolyi** [comment]
Not sure where you raise an "original OSError" (stated in the changelog), but you might want to use a different error instead of EnvironmentError, if the two aren't the same?
