### ISSUE TITLE
how to auto-install pkgconfig and use it from setup.py?

### ISSUE THREAD

**Issue by ThomasWaldmann** [matze/pkgconfig#61]
at borgbackup, we use `pkgconfig` to locate some libraries we need for building some C extensions (using Cython) for our python code.

we have documented that `pkgconfig` MUST be installed before `setup.py` is invoked, but who reads docs? :-)

because `pkgconfig` is already needed at import time of `setup.py` (to build the C extensions), before `setup(...)` is invoked, we can't use `setup_requires` to have `pkgconfig` pulled automatically.

is there a way to have it pull `pkgconfig` automagically somehow?

https://github.com/borgbackup/borg/blob/1.2.0/setup.py

**Comment by matze** [comment]
Hmm, other then vendoring `pkgconfig` or installing directly from source up-front via `pip` I don't think this is possible.

**Comment by ThomasWaldmann** [comment]
Hmm, considering that `pkgconfig` is just a single module / single file i would need to vendor (== put besides `setup.py`), that sounds like a good idea.

Anything from your side that might make this more complicated than it seems?

**Comment by ThomasWaldmann** [comment]
Hmm, OTOH, even if we vendor `pkgconfig` python module, it will still need the `pkg-config` cli tool and that can be missing, too.

**Comment by matze** [comment]
> Anything from your side that might make this more complicated than it seems?

Sorry for the late reply. No, I think it's a rational thing to do. Just look hat what [pip](https://github.com/pypa/pip/tree/main/src/pip/_vendor) vendors, that's a whole different level.

**Comment by ThomasWaldmann** [comment]
Migrating to `pyproject.toml` (as one should do anyway nowadays) solves this.

In case of borgbackup we use this:

```
[build-system]
requires = ["setuptools", "wheel", "pkgconfig", "Cython>=3.0.3", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```
