### ISSUE TITLE
Supported python versions?

### ISSUE THREAD

**Issue by ThomasWaldmann** [matze/pkgconfig#68]
Guess we should discuss what the supported python versions should be.

README: 3.3+

Pypi package metadata: https://pypi.org/project/pkgconfig/ inconsistent: >=3.3 <4.0 at one place, >=3.4 <=3.9 at another.

Poetry: seems to suggest >= 3.3.

Tox: py33 .. py312

One approach would be to assume "not tested == broken" and then adjust the supported versions to exactly what is tested in CI.

**Comment by ThomasWaldmann** [comment]
Note: #70 will do CI tests on py38,39,310,311,312 after it is merged.

**Comment by ThomasWaldmann** [comment]
py38 will run out of upstream support at 2024-10 (see python.org downloads).

All older versions are upstream-unsupported already, but maybe get support from Linux or other distributors still?

**Comment by ThomasWaldmann** [comment]
Considering that pkgconfig can be quite essential for building other packages and some people run stuff on very old systems, I guess we shouldn't kick out upstream-unsupported pythons immediately - as long as "supporting" (CI testing) on them does not cause pains.

**Comment by ThomasWaldmann** [comment]
BTW, would be good to decide on this / get this consistent **BEFORE** next pypi.org release, so that the metadata there will be also fixed.

**Comment by ThomasWaldmann** [comment]
RHEL7 is still supported, older versions are not.

Python 3 is distributed in versions 3.6, 3.8, and 3.9, provided by the python36, python38, and python39 modules on RHEL 7.

So, looks like even users of that rather old dist could easily work with py39.

**Comment by ThomasWaldmann** [comment]
@matze I can help with a PR making this all consistent, just need to know which python versions you want to support for pkgconfig.

**Comment by matze** [comment]
IMHO dropping everything EOL'd or close to is fine. So Python 3.9+ is okay :+1: Thanks for taking the lead in this!
